config/routes.rb
Rails.application.routes.draw do 
  resources :kittens

  get 'pages/home'
  get 'pages/winners'
  
  resources :tournaments

  devise_for :users

  root 'pages#home'

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
	has_and_belongs_to_many :tournaments
end

app/models/kittens_tournament.rb
class KittensTournament < ActiveRecord::Base
  belongs_to :kitten
  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :kittens
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tournaments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :username
		devise_parameter_sanitizer.for(:account_update) << :username
	end
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @kittens = Kitten.all
    respond_with(@kittens)
  end

  def show
    respond_with(@kitten)
  end

  def new
    @kitten = Kitten.new
    respond_with(@kitten)
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)
    @kitten.save
    respond_with(@kitten)
  end

  def update
    @kitten.update(kitten_params)
    respond_with(@kitten)
  end

  def destroy
    @kitten.destroy
    respond_with(@kitten)
  end

  private
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    def kitten_params
      params.require(:kitten).permit(:url, :wins)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def winners
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
	attr_accessor :kittens, :tournament

  def index
    @tournaments = Tournament.all
  end

  def new
  	@tournament = Tournament.create(user_id: current_user.id)
    @tournament.save

    @kittens = HTTParty.get("http://pv.pop.umn.edu/images/").parsed_response["data"]

    @kittens.each do |kitten_url|
      @kitten = Kitten.create(url: kitten_url, wins: 0)
      @tournament.kittens << @kitten
    end
    @tournament.save

    redirect_to @tournament
  end

  # def create
  # 	@tournament = Tournament.create(user_id: current_user.id)
  # 	@tournament.save

  # 	@kittens = HTTParty.get("http://pv.pop.umn.edu/images/").parsed_response["data"]

  # 	@kittens.each do |kitten_url|
  # 		@tournament.kittens.build(url: kitten_url, wins: 0).save
  # 	end
  # 	@tournament.save

  # 	redirect_to @tournament
  # end

  def show
    @tournament = Tournament.find(params[:id])
    @kittens = @tournament.kittens
  end

  # def round1
  # 	@kittens
  # end

  # def round2
  # end

  # def round3
  # end

  # def round4
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
  <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
      <% @kitten.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :wins %><br>
    <%= f.number_field :wins %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Editing Kitten</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitten %> |
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kittens</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Wins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.url %></td>
        <td><%= kitten.wins %></td>
        <td><%= link_to 'Show', kitten %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'form' %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @kitten.url %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @kitten.wins %>
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">Kitty Karnival</div>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Winners", pages_winners_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      	<li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kitty Karnival</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'tournaments' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to the Kitty Karnival!</h1>
     <% if user_signed_in? %>
          <%= link_to "Begin Tournament", new_tournament_path, class: "btn btn-primary btn-lg" %>
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/pages/winners.html.erb
<h1>Here are the Winners:</h1>

app/views/tournaments/index.html.erb
<h1>Which Kitty is the Kutest??</h1>
	

app/views/tournaments/new.html.erb
<h1>Which Kitty is the Kutest??</h1>
	<%= link_to "Begin Round 1", tournament_path(current_user, @tournament) %><br>

app/views/tournaments/show.html.erb
<div id="round1">
	<h1 id="title" style="text-align: center">Round 1</h1>
	<div class="center">
		<div class="competitor" id="1"><%= image_tag(@kittens[0].url, size: '200') %></div> VS <div class="competitor" id="2"><%= image_tag(@kittens[1].url, size: '200') %></div>
		<div class="competitor" id="3"><%= image_tag(@kittens[2].url, size: '200') %></div> VS <div class="competitor" id="4"><%= image_tag(@kittens[3].url, size: '200') %></div>
		<div class="competitor" id="5"><%= image_tag(@kittens[4].url, size: '200') %></div> VS <div class="competitor" id="6"><%= image_tag(@kittens[5].url, size: '200') %></div>
		<div class="competitor" id="7"><%= image_tag(@kittens[6].url, size: '200') %></div> VS <div class="competitor" id="8"><%= image_tag(@kittens[7].url, size: '200') %></div>
		<div class="competitor" id="9"><%= image_tag(@kittens[8].url, size: '200') %></div> VS <div class="competitor" id="10"><%= image_tag(@kittens[9].url, size: '200') %></div>
		<div class="competitor" id="11"><%= image_tag(@kittens[10].url, size: '200') %></div> VS <div class="competitor" id="12"><%= image_tag(@kittens[11].url, size: '200') %></div>
		<div class="competitor" id="13"><%= image_tag(@kittens[12].url, size: '200') %></div> VS <div class="competitor" id="14"><%= image_tag(@kittens[13].url, size: '200') %></div>
		<div class="competitor" id="15"><%= image_tag(@kittens[14].url, size: '200') %></div> VS <div class="competitor" id="16"><%= image_tag(@kittens[15].url, size: '200') %></div>
	</div>
</div>

<div id="round2">
	<h1 id="title" style="text-align: center">Round 2</h1>
	<div class="center">
		<div class="competitor" id="1"><p>Game 1 Winner</p></div> VS <div class="competitor" id="2"><p>Game 2 Winner</p></div>

		<div class="competitor" id="3"><p>Game 3 Winner</p></div> VS <div class="competitor" id="4"><p>Game 4 Winner</p></div>

		<div class="competitor" id="5"><p>Game 5 Winner</p></div> VS <div class="competitor" id="6"><p>Game 6 Winner</p></div>

		<div class="competitor" id="7"><p>Game 7 Winner</p></div> VS <div class="competitor" id="8"><p>Game 8 Winner</p></div>
	</div>
</div>

<div id="round3">
	<h1 id="title" style="text-align: center">Round 3</h1>
	<div class="center">
		<div class="competitor" id="1"><p>Round 2 Game 1 Winner</p></div> VS <div class="competitor" id="2"><p>Round 2 Game 2 Winner</p></div>

		<div class="competitor" id="3"><p>Round 2 Game 3 Winner</p></div> VS <div class="competitor" id="4"><p>Round 2 Game 4 Winner</p></div>
	</div>
</div>

<div id="round4">
	<h1 id="title" style="text-align: center">Round 4</h1>
	<div class="center">
		<div class="competitor" id="1"><p>Game 1 Winner</p></div> VS <div class="competitor" id="2"><p>Game 2 Winner</p></div>
	</div>
</div>

<div id="winner">
	<h1 id="title" style="text-align: center">Winner 4</h1>
	<div class="center">
		<div class="competitor" id="1"><p>Tournament Winner</p></div>
	</div>
</div>